### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Connection'

### ISSUE THREAD

**Issue by fotoKrille** [thelinuxkid/bitcoinquery#1]
Kristers-MacBook-Pro:bitcoinquery fotoKrille$ .virtual/bin/blockchain-collect collect.conf
Traceback (most recent call last):
  File ".virtual/bin/blockchain-collect", line 9, in <module>
    load_entry_point('bitcoinquery==0.0.2', 'console_scripts', 'blockchain-collect')()
  File "build/bdist.macosx-10.6-intel/egg/bitcoinquery/cli.py", line 143, in blockchain_collect
  File "build/bdist.macosx-10.6-intel/egg/bitcoinquery/cli.py", line 45, in parse_args
  File "build/bdist.macosx-10.6-intel/egg/bitcoinquery/util/mongodb.py", line 68, in database
AttributeError: 'module' object has no attribute 'Connection'

**Comment by thelinuxkid** [comment]
Which version of mongodb.py are you using?
